<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Password;
use Inertia\Inertia;

/**
 * Handles "forgot password" flow:
 *   GET  /forgot-password  — show email form
 *   POST /forgot-password  — send password reset link via email
 *
 * The reset link is generated by Laravel's Password broker, which:
 *   1. Looks up the user by email
 *   2. Generates a signed token (stored in `password_reset_tokens`)
 *   3. Sends a Markdown email with the URL `/reset-password/{token}`
 *
 * Currently uses the `log` mail driver (writes to storage/logs/laravel.log)
 * so reset links land in the log file for testing. Swap MAIL_MAILER=smtp in
 * .env once a real mail provider is configured.
 */
class PasswordResetLinkController extends Controller
{
    public function create(Request $request)
    {
        return Inertia::render('Auth/ForgotPassword', [
            'status' => $request->session()->get('status'),
        ]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'email' => 'required|email',
        ]);

        // Password::sendResetLink returns Password::RESET_LINK_SENT on success
        // or Password::INVALID_USER when the email doesn't exist. We respond
        // with the same generic status either way to avoid leaking which
        // addresses are registered (standard Laravel auth UX).
        $status = Password::sendResetLink(
            $request->only('email')
        );

        if ($status === Password::RESET_LINK_SENT) {
            return back()->with('flash', [
                'type' => 'success',
                'message' => 'Check your inbox — we just sent you a link to reset your password.',
            ]);
        }

        // Failure (unknown email, throttled, etc.) \u2014 single field-level
        // error only, no toast. The success flash above is the only toast.
        // __($status) resolves to Laravel's framework translation key
        // (e.g. "We can't find a user with that email address.") even
        // without a local lang/ directory.
        return back()->withErrors(['email' => __($status)]);
    }
}
