<?php

namespace App\Providers;

use App\Models\AiAgent;
use App\Policies\AiAgentPolicy;
use Illuminate\Auth\Notifications\ResetPassword;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        Gate::policy(AiAgent::class, AiAgentPolicy::class);

        // Customize the password reset notification email. The default Laravel
        // template is plain text + ugly inline button. Ours uses the ThinkChat
        // brand header (logo + violet/purple gradient), a gradient CTA button
        // matching the in-app design, expiry callout, and a security note.
        // The HTML view lives at resources/views/emails/password-reset.blade.php.
        ResetPassword::toMailUsing(function ($notifiable, $token) {
            $resetUrl = url(route('password.reset', [
                'token' => $token,
                'email' => $notifiable->getEmailForPasswordReset(),
            ], false));

            // Expiration time in minutes, configured in config/auth.php.
            $expiresIn = config('auth.passwords.'.config('auth.defaults.passwords').'.expire');

            // Embed the brand logo as a base64 data URI so it renders in every
            // email client. Gmail/Outlook/Apple Mail refuse to load http://
            // images by default, and the original 1.4MB PNG also trips
            // image-proxy timeouts on Ethereal + many real clients. The
            // email-sized PNG is generated by scripts/build-email-logo.php.
            // Falls back to a URL if the file is missing so a fresh checkout
            // still works (template's own ?? fallback handles that).
            $logoDataUri = null;
            $emailLogoPath = public_path('img/logo-brand-email.png');
            if (is_file($emailLogoPath)) {
                $logoDataUri = 'data:image/png;base64,' . base64_encode(file_get_contents($emailLogoPath));
            }

            return (new \Illuminate\Notifications\Messages\MailMessage)
                ->subject('Reset your ThinkChat password')
                ->view('emails.password-reset', [
                    'userName'  => $notifiable->name ?? null,
                    'resetUrl'  => $resetUrl,
                    'logoUrl'   => $logoDataUri ?? url('/img/logo-brand.png'),
                    'expiresIn' => $expiresIn,
                ]);
        });
    }
}

